### ISSUE TITLE
-OPERACIONES BASICAS-

### ISSUE THREAD

**Issue by Yesus-12** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-Yesus-12#1]
[Sistemas numericos.Binario,octal-hexadecimal.JESUS.docx](https://github.com/user-attachments/files/16844388/Sistemas.numericos.Binario.octal-hexadecimal.JESUS.docx)

**Comment by JordanMendoza401** [comment]
Portada 0/25
Procedimiento 20/25
Figuras ilustrativas y fotografías 10/25
Resultados y Conclusiones 18/25
Calificación de la práctica: 9.6

**Comment by Yesus-12** [comment]
[Sistemas.numericos.Matematicas discretas.JESUS.docx](https://github.com/user-attachments/files/16920309/Sistemas.numericos.Matematicas.discretas.JESUS.docx)

**Comment by JordanMendoza401** [comment]
Portada 25/25
Procedimiento 24/25
Figuras ilustrativas y fotografías 20/25
Resultados y Conclusiones 25/25
Calificación de la práctica: 18.8
